use ast::types::{CommentBlock, ControlFlowNode};
/// Contains methods to parse Fortran code into a tree-sitter Tree and utilities to simplify the
/// navigation of a Tree.
use std::cmp::Ordering;
use std::error::Error;
use std::fmt::{Debug, Display, Formatter};
use std::hash::{Hash, Hasher};
use std::num::NonZeroU16;
use std::str::Utf8Error;
use tree_sitter::{Point, Range};

use anyhow::Result;
use fortitude_macros::{field, kind};
use ruff_diagnostics::Edit;
use ruff_source_file::LineRanges;
use ruff_text_size::{TextRange, TextSize};

pub mod ast;
pub mod traits;
pub mod whitespace;

use crate::traits::TextRanged;
use crate::whitespace::{has_leading_content, has_trailing_content};

/// A tree that represents the syntactic structure of a source code file.
///
/// It stores its text and filepath, and uses and is used by other [`yak_sitter`](crate) wrappers.
#[derive(Clone, Debug)]
pub struct Tree<'source> {
    tree: tree_sitter::Tree,
    source: &'source str,
}

/// A single node on a syntax [`Tree`].
///
/// It can access its text and filepath, and uses and is used by other [`yak_sitter`](crate)
/// wrappers.
#[derive(Clone, Copy)]
pub struct Node<'tree> {
    node: tree_sitter::Node<'tree>,
    tree: &'tree Tree<'tree>,
}

/// Wrapper around `usize` (aka node id)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct NodeId(usize);

/// A stateful object for walking a syntax tree efficiently.
#[derive(Clone)]
pub struct TreeCursor<'tree> {
    cursor: tree_sitter::TreeCursor<'tree>,
    tree: &'tree Tree<'tree>,
}

/// A stateful object that this is used to produce a Tree based on some source code
#[repr(transparent)]
pub struct Parser(tree_sitter::Parser);

/// An opaque object that defines how to parse a particular language.
///
/// The code for each Language is generated by the Tree-sitter CLI.
pub type Language = tree_sitter::Language;
/// Re-exports [`tree_sitter::LanguageRef`]
pub type LanguageRef<'a> = tree_sitter::LanguageRef<'a>;
/// An error that occurred when trying to assign an incompatible [`Language`] to a [`Parser`]
pub type LanguageError = tree_sitter::LanguageError;

/// Error from parsing a tree
#[derive(Debug)]
pub enum TreeParseError {
    IO(std::io::Error),
    ParsingFailed,
    NotUtf8(Utf8Error),
}

pub struct DepthFirstIterator<'a> {
    cursor: TreeCursor<'a>,
}

impl<'a> Iterator for DepthFirstIterator<'a> {
    type Item = Node<'a>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.cursor.goto_first_child() {
            return Some(self.cursor.node());
        }
        if self.cursor.goto_next_sibling() {
            return Some(self.cursor.node());
        }
        while self.cursor.goto_parent() {
            if self.cursor.goto_next_sibling() {
                return Some(self.cursor.node());
            }
        }
        None
    }
}

pub struct DepthFirstIteratorExcept<'a> {
    cursor: TreeCursor<'a>,
    exceptions: &'a [u16],
}

impl<'a> Iterator for DepthFirstIteratorExcept<'a> {
    type Item = Node<'a>;

    fn next(&mut self) -> Option<Self::Item> {
        // ignore exception list if we're at a depth of 0
        if (self.cursor.depth() == 0 || !self.exceptions.contains(&self.cursor.node().kind_id()))
            && self.cursor.goto_first_child()
        {
            return Some(self.cursor.node());
        }
        if self.cursor.goto_next_sibling() {
            return Some(self.cursor.node());
        }
        while self.cursor.goto_parent() {
            if self.cursor.goto_next_sibling() {
                return Some(self.cursor.node());
            }
        }
        None
    }
}

pub struct AncestorsIterator<'a> {
    node: Node<'a>,
}

impl<'a> Iterator for AncestorsIterator<'a> {
    type Item = Node<'a>;

    fn next(&mut self) -> Option<Self::Item> {
        self.node = self.node.parent()?;
        Some(self.node)
    }
}

impl Parser {
    /// Create a new parser for the given language. See [`tree_sitter::Parser::set_language`]
    #[inline]
    pub fn new(language: &Language) -> Result<Self, LanguageError> {
        let mut parser = tree_sitter::Parser::new();
        parser.set_language(language)?;
        Ok(Self(parser))
    }

    /// Parse a string. See [`tree_sitter::Parser::parse`].
    ///
    /// The path is stored as metadata that can be accessed from nodes. If you don't need this, pass
    /// `None`.
    #[inline]
    pub fn parse<'source>(
        &mut self,
        source: &'source str,
        old_tree: Option<&Tree>,
    ) -> Result<Tree<'source>, TreeParseError> {
        let tree = self
            .0
            .parse(source, old_tree.map(|t| &t.tree))
            .ok_or(TreeParseError::ParsingFailed)?;
        Ok(Tree::new(tree, source)?)
    }
}

impl<'source> Tree<'source> {
    /// Wrap the tree and its associated text.
    ///
    /// Note that the wrappers expect and assume UTF-8, so this returns `Err` if the text is not
    /// valid UTF-8.
    #[inline]
    fn new(tree: tree_sitter::Tree, source: &'source str) -> Result<Self, Utf8Error> {
        Ok(Self { tree, source })
    }

    /// Get the underlying text. This includes text which isn't in the `Self::included_ranges`
    #[inline]
    pub fn text(&self) -> &str {
        self.source
    }

    /// Get the root node.
    #[inline]
    pub fn root_node(&self) -> Node<'_> {
        // SAFETY: The node is from this tree
        unsafe { Node::new(self.tree.root_node(), self) }
    }

    /// Create a cursor starting at the root node
    #[inline]
    pub fn walk(&self) -> TreeCursor<'_> {
        TreeCursor::new(self.tree.walk(), self)
    }

    /// Get the language used to parse the tree.
    #[inline]
    pub fn language(&self) -> LanguageRef<'_> {
        self.tree.language()
    }
}

impl<'tree> Node<'tree> {
    /// Wrap a [`tree_sitter::Node`]. Requires its associated [`Tree`] for convenience methods.
    ///
    /// # Safety
    /// The node must be from the given tree.
    #[inline]
    pub unsafe fn new(node: tree_sitter::Node<'tree>, tree: &'tree Tree) -> Self {
        Self { node, tree }
    }

    /// Gets the node id, which is represented by its address.
    ///
    /// Nodes from separate trees are guaranteed to have different ids iff both trees are alive, but
    /// a node which is no longer alive may have the same id as a different node which is. The
    /// tree-sitter docs specify that a if a tree is created from an older tree, nodes may be reused
    /// and from the old tree and these will have the same id.
    ///
    /// See [`tree_sitter::Node::id`].
    #[inline]
    pub fn id(&self) -> NodeId {
        NodeId::of_ts(self.node)
    }

    /// Get the node's kind. See [`tree_sitter::Node::kind`]
    #[inline]
    pub fn kind(&self) -> &'static str {
        self.node.kind()
    }

    /// Get the node's kind_id. See [`tree_sitter::Node::kind_id`]
    #[inline]
    pub fn kind_id(&self) -> u16 {
        self.node.kind_id()
    }

    /// Get the node's symbol name as it appears in the grammar. See
    /// [`tree_sitter::Node::grammar_name`]
    #[inline]
    pub fn grammar_name(&self) -> &'static str {
        self.node.grammar_name()
    }

    /// Check if the node is named. See [`tree_sitter::Node::is_named`]
    #[inline]
    pub fn is_named(&self) -> bool {
        self.node.is_named()
    }

    /// Check if the node is missing. See [`tree_sitter::Node::is_missing`]
    #[inline]
    pub fn is_missing(&self) -> bool {
        self.node.is_missing()
    }

    /// Check if the node is extra. See [`tree_sitter::Node::is_extra`]
    #[inline]
    pub fn is_extra(&self) -> bool {
        self.node.is_extra()
    }

    /// Check if the node is an error. See [`tree_sitter::Node::is_error`]
    #[inline]
    pub fn is_error(&self) -> bool {
        self.node.is_error()
    }

    /// Check if the node has an error. See [`tree_sitter::Node::has_error`]
    #[inline]
    pub fn has_error(&self) -> bool {
        self.node.has_error()
    }

    /// Check if the node has changes. See [`tree_sitter::Node::has_changes`]
    #[inline]
    pub fn has_changes(&self) -> bool {
        self.node.has_changes()
    }

    /// Get the byte offsets where this node starts
    #[inline]
    pub fn start_byte(&self) -> usize {
        self.node.start_byte()
    }

    /// Get the byte offsets where this node ends
    #[inline]
    pub fn end_byte(&self) -> usize {
        self.node.end_byte()
    }

    /// Get the row and column where this node starts
    #[inline]
    pub fn start_position(&self) -> Point {
        self.node.start_position()
    }

    /// Get the row and column where this node ends
    #[inline]
    pub fn end_position(&self) -> Point {
        self.node.end_position()
    }

    /// Get the byte range where this node is located
    #[inline]
    pub fn byte_range(&self) -> std::ops::Range<usize> {
        self.node.byte_range()
    }

    #[inline]
    pub fn range(&self) -> Range {
        self.node.range()
    }

    /// Get the node's text.
    ///
    /// **Warning:** the return value is unspecified if the tree is edited.
    #[inline]
    pub fn text(&self) -> &'tree str {
        // SAFETY: We checked this was UTF-8 when we opened the file
        let byte_text = &self.tree.source.as_bytes()[self.byte_range()];
        unsafe { std::str::from_utf8_unchecked(byte_text) }
    }

    /// Get the node's named and unnamed children. See [`tree_sitter::Node::children`]
    #[inline]
    pub fn children<'a>(
        &self,
        cursor: &'a mut TreeCursor<'tree>,
    ) -> impl ExactSizeIterator<Item = Node<'tree>> + 'a {
        let tree = self.tree;
        // SAFETY: Same tree
        self.node
            .children(&mut cursor.cursor)
            .map(move |node| unsafe { Node::new(node, tree) })
    }

    /// Get the node's named children. See [`tree_sitter::Node::named_children`]
    #[inline]
    pub fn named_children<'a>(
        &self,
        cursor: &'a mut TreeCursor<'tree>,
    ) -> impl ExactSizeIterator<Item = Node<'tree>> + 'a {
        let tree = self.tree;
        // SAFETY: Same tree
        self.node
            .named_children(&mut cursor.cursor)
            .map(move |node| unsafe { Node::new(node, tree) })
    }

    /// Get the number of (named and unnamed) children
    #[inline]
    pub fn child_count(&self) -> usize {
        self.node.child_count()
    }

    /// Get the number of named children
    #[inline]
    pub fn named_child_count(&self) -> usize {
        self.node.named_child_count()
    }

    /// Get the node's immediate parent
    #[inline]
    pub fn parent(&self) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .parent()
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's immediate next (named or unnamed) sibling
    #[inline]
    pub fn next_sibling(&self) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .next_sibling()
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's immediate next named sibling
    #[inline]
    pub fn next_named_sibling(&self) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .next_named_sibling()
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's immediate previous (named or unnamed) sibling
    #[inline]
    pub fn prev_sibling(&self) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .prev_sibling()
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's immediate previous named sibling
    #[inline]
    pub fn prev_named_sibling(&self) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .prev_named_sibling()
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's (named or unnamed) child at the given index. See [`tree_sitter::Node::child`]
    #[inline]
    pub fn child(&self, i: usize) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .child(u32::try_from(i).ok()?)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's named child at the given index. See [`tree_sitter::Node::named_child`]
    #[inline]
    pub fn named_child(&self, i: usize) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .named_child(i.try_into().ok()?)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's last (named or unnamed) child
    #[inline]
    pub fn last_child(&self) -> Option<Node<'tree>> {
        // .child is already bounds-checked so we use wrapping_sub for iff the count is 0
        self.child(self.child_count().wrapping_sub(1))
    }

    /// Get the node's last named child
    #[inline]
    pub fn last_named_child(&self) -> Option<Node<'tree>> {
        // .named_child is already bounds-checked so we use wrapping_sub for iff the count is 0
        self.named_child(self.named_child_count().wrapping_sub(1))
    }

    /// Get the node's first child of the given kind, named or unnamed.
    ///
    /// The cursor is used to iterate the node's immediate children in order to find said child.
    #[inline]
    pub fn child_of_kind(&self, kind: &str, cursor: &mut TreeCursor<'tree>) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .named_children(&mut cursor.cursor)
            .find(|node| node.kind() == kind)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's children of the given kind, named or unnamed.
    ///
    /// The cursor is used to iterate the node's immediate children in order to find said child.
    #[inline]
    pub fn children_of_kind<'a>(
        &self,
        kind: &'a str,
        cursor: &'a mut TreeCursor<'tree>,
    ) -> impl Iterator<Item = Node<'tree>> + 'a {
        // SAFETY: Same tree
        self.node
            .named_children(&mut cursor.cursor)
            .filter(move |node| node.kind() == kind)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the first child with the given field name
    #[inline]
    pub fn child_by_field_name(&self, field_name: &str) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .child_by_field_name(field_name)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get this node's child with the given numerical field id.
    ///
    /// See also [`child_by_field_name`](Node::child_by_field_name). You can
    /// convert a field name to an id using [`Language::field_id_for_name`].
    #[inline]
    pub fn child_by_field_id(&self, field_id: u16) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .child_by_field_id(field_id)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's children with the given field name
    #[inline]
    pub fn children_by_field_name<'a>(
        &self,
        field_name: &str,
        c: &'a mut TreeCursor<'tree>,
    ) -> impl Iterator<Item = Node<'tree>> + 'a {
        // SAFETY: Same tree
        self.node
            .children_by_field_name(field_name, &mut c.cursor)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the node's children with the given field name
    #[inline]
    pub fn children_by_field_id<'a>(
        &self,
        field_id: NonZeroU16,
        c: &'a mut TreeCursor<'tree>,
    ) -> impl Iterator<Item = Node<'tree>> + 'a {
        // SAFETY: Same tree
        self.node
            .children_by_field_id(field_id, &mut c.cursor)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }
    /// Get the field name of the child at the given index
    #[inline]
    pub fn field_name_for_child(&self, i: usize) -> Option<&'static str> {
        self.node.field_name_for_child(i as u32)
    }

    /// Get the field name of the named child at the given index
    #[inline]
    pub fn field_name_for_named_child(&self, i: usize) -> Option<&'static str> {
        self.node.field_name_for_named_child(i as u32)
    }

    /// Get the node's field name.
    ///
    /// This is done by looking at the parent's children and finding the one that matches this node,
    /// then returning its field name, hence the need for a cursor.
    pub fn field_name(&self, cursor: &mut TreeCursor<'tree>) -> Option<&'static str> {
        self.parent().and_then(|parent| {
            let i = parent
                .children(cursor)
                .position(|x| x == *self)
                .expect("node not one of its parent's children");
            parent.field_name_for_child(i)
        })
    }

    /// Get a [`TreeCursor`] that points to this node.
    ///
    /// Unlike tree-sitter's cursors, this one can also reach its siblings and parents, albeit with
    /// degraded performance.
    #[inline]
    pub fn walk(&self) -> TreeCursor<'tree> {
        TreeCursor::new(self.node.walk(), self.tree)
    }

    /// Print the node as an s-expression
    #[inline]
    pub fn to_sexp(&self) -> String {
        self.node.to_sexp()
    }

    /// Get the node's number of descendants, including one for the node itself.
    #[inline]
    pub fn descendant_count(&self) -> usize {
        self.node.descendant_count()
    }

    /// Get the smallest node within this node that spans the given byte range.
    #[inline]
    pub fn descendant_for_byte_range(&self, start: usize, end: usize) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .descendant_for_byte_range(start, end)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    /// Get the smallest named node within this node that spans the given byte range.
    #[inline]
    pub fn named_descendant_for_byte_range(&self, start: usize, end: usize) -> Option<Node<'tree>> {
        // SAFETY: Same tree
        self.node
            .named_descendant_for_byte_range(start, end)
            .map(|node| unsafe { Node::new(node, self.tree) })
    }

    pub fn descendants(&self) -> impl Iterator<Item = Node<'_>> {
        DepthFirstIterator {
            cursor: self.walk(),
        }
    }

    pub fn named_descendants(&self) -> impl Iterator<Item = Node<'_>> {
        self.descendants().filter(|&x| x.is_named())
    }

    pub fn descendants_except(&self, exceptions: &'tree [u16]) -> impl Iterator<Item = Node<'_>> {
        DepthFirstIteratorExcept {
            cursor: self.walk(),
            exceptions,
        }
    }

    pub fn ancestors(&self) -> impl Iterator<Item = Node<'_>> {
        AncestorsIterator { node: *self }
    }

    pub fn child_with_name(&self, name: &str) -> Option<Node<'tree>> {
        self.named_children(&mut self.walk())
            .find(|x| x.kind() == name)
    }

    pub fn child_with_id(&self, kind_id: u16) -> Option<Node<'tree>> {
        self.children(&mut self.walk())
            .find(|x| x.kind_id() == kind_id)
    }

    pub fn kwarg<S: AsRef<str>>(&self, keyword: S) -> Option<Node<'_>> {
        let keyword = keyword.as_ref();
        self.named_children(&mut self.walk()).find(|child| {
            child.kind_id() == kind!("keyword_argument")
                && child
                    .child_by_field_id(field!("name").into())
                    .is_some_and(|n| n.text().eq_ignore_ascii_case(keyword))
        })
    }

    pub fn kwarg_value<S: AsRef<str>>(&self, keyword: S) -> Option<Node<'_>> {
        self.kwarg(keyword)?
            .child_by_field_id(field!("value").into())
    }

    pub fn kwarg_exists<S: AsRef<str>>(&self, keyword: S) -> bool {
        self.kwarg(keyword).is_some()
    }

    pub fn indentation(&self) -> String {
        let src = self.tree.text();
        let offset = self.start_textsize();
        let line_start = src.line_start(offset);
        let line = &src[TextRange::new(line_start, offset)];
        line.chars().take_while(|&c| c.is_whitespace()).collect()
    }

    pub fn indentation_ignore_stmt_label(&self) -> String {
        let src = self.tree.text();
        let start_byte = self.start_textsize();
        let start_line = src.line_start(start_byte);
        let width = (start_byte - start_line).to_usize();
        format!("{:width$}", " ")
    }

    pub fn edit_delete(&self) -> Edit {
        let src = self.tree.text();
        if has_leading_content(self.start_textsize(), src)
            || has_trailing_content(self.end_textsize(), src)
        {
            Edit::range_deletion(self.textrange())
        } else {
            // If deletion results in an empty line (or multiple), remove it
            Edit::range_deletion(src.full_lines_range(self.textrange()))
        }
    }

    pub fn edit_replacement(&self, content: String) -> Edit {
        // The node might include the newline as part of the
        // end-of-statement child, so don't include trailing
        // whitespace in the replacement
        let text = self.text();
        let len = text.trim().len();
        let start = self.start_textsize();
        let end = start + TextSize::try_from(len).unwrap();

        Edit::replacement(content, start, end)
    }

    pub fn next_non_comment_sibling(&self) -> Option<Node<'tree>> {
        let mut sibling = self.next_named_sibling();
        while let Some(next_sibling) = sibling {
            if next_sibling.kind() != "comment" {
                return Some(next_sibling);
            }
            sibling = next_sibling.next_named_sibling();
        }
        None
    }

    pub fn next_non_comment_statement(&self) -> Option<Node<'tree>> {
        if let Some(next) = self.next_non_comment_sibling() {
            return Some(next);
        }
        let mut current = *self;
        while let Some(parent) = current.parent() {
            if let Some(sibling) = parent.next_non_comment_sibling() {
                return Some(sibling);
            }
            current = parent;
        }
        None
    }

    pub fn inline_if_statement(&self) -> bool {
        self.kind_id() == kind!("if_statement")
            && self.child_with_id(kind!("end_if_statement")).is_none()
    }

    pub fn prev_non_comment_sibling(&self) -> Option<Node<'tree>> {
        let mut sibling = self.prev_named_sibling();
        while let Some(prev_sibling) = sibling {
            if prev_sibling.kind_id() != kind!("comment") {
                return Some(prev_sibling);
            }
            sibling = prev_sibling.prev_named_sibling();
        }
        None
    }

    pub fn next_statement_label_sibling<S: AsRef<str>>(&self, label: S) -> Option<Node<'tree>> {
        let mut sibling = self.next_named_sibling();
        while let Some(next_sibling) = sibling {
            if next_sibling.kind_id() == kind!("statement_label")
                && next_sibling.text() == label.as_ref()
            {
                return Some(next_sibling);
            }
            sibling = next_sibling.next_named_sibling();
        }
        None
    }

    pub fn next_statement_label<S: AsRef<str>>(&self, label: S) -> Option<Node<'tree>> {
        if let Some(next) = self.next_statement_label_sibling(label.as_ref()) {
            return Some(next);
        }
        let mut current = *self;
        while let Some(parent) = current.parent() {
            if let Some(sibling) = parent.next_statement_label_sibling(label.as_ref()) {
                return Some(sibling);
            }
            current = parent;
        }
        None
    }

    pub fn module_name(&self) -> Option<&'tree str> {
        if self.kind_id() != kind!("use_statement") {
            return None;
        }
        Some(self.child_with_id(kind!("module_name"))?.text())
    }

    pub fn prev_attached_comment_block(&self) -> Option<CommentBlock> {
        let mut comments = Vec::new();
        let mut prev_comment = *self;

        while let Some(comment) = prev_comment.prev_named_sibling() {
            if comment.kind() != "comment" {
                break;
            }
            if comment.end_position().row != prev_comment.start_position().row.saturating_sub(1) {
                break;
            }
            comments.push(comment);
            prev_comment = comment;
        }

        // We've worked backwards, so reverse to get in correct order
        comments.reverse();
        CommentBlock::try_from_node_range(comments).ok()
    }

    pub fn try_to_controlflow(self) -> Option<ControlFlowNode<'tree>> {
        ControlFlowNode::maybe_from(self)
    }

    pub fn prev_line_continuation(&self) -> Option<Node<'tree>> {
        let mut sibling = self.prev_sibling();
        while let Some(prev_sibling) = sibling {
            if prev_sibling.kind() == "&" && !prev_sibling.textrange().is_empty() {
                return Some(prev_sibling);
            }
            sibling = prev_sibling.prev_sibling();
        }
        None
    }

    pub fn next_line_continuation(&self) -> Option<Node<'tree>> {
        let mut sibling = self.next_sibling();
        while let Some(next_sibling) = sibling {
            if next_sibling.kind() == "&" {
                return Some(next_sibling);
            }
            sibling = next_sibling.next_sibling();
        }
        None
    }
}

impl<'tree> PartialEq for Node<'tree> {
    #[inline]
    fn eq(&self, other: &Node<'tree>) -> bool {
        self.id() == other.id()
    }
}

impl<'tree> Eq for Node<'tree> {}

impl<'tree> PartialOrd for Node<'tree> {
    /// If not equal, compares based on source position, then filepath, then address.
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl<'tree> Ord for Node<'tree> {
    /// If not equal, compares based on source position, then filepath, then address.
    fn cmp(&self, other: &Self) -> Ordering {
        if self.id() == other.id() {
            Ordering::Equal
        } else if std::ptr::eq(self.tree as *const _, other.tree as *const _) {
            self.start_byte()
                .cmp(&other.start_byte())
                .then(self.end_byte().cmp(&other.end_byte()))
        } else {
            self.id().0.cmp(&other.id().0)
        }
    }
}

impl<'tree> Hash for Node<'tree> {
    #[inline]
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.id().hash(state)
    }
}

impl<'tree> TreeCursor<'tree> {
    /// Wrap a [`tree-sitter::TreeCursor`].
    ///
    /// You must also provide the tree and whether the cursor is at the root node, which are used to
    /// access parent and siblings on cursors that are not rooted.
    #[inline]
    fn new(cursor: tree_sitter::TreeCursor<'tree>, tree: &'tree Tree) -> Self {
        Self { cursor, tree }
    }

    /// Gets the cursor's current node
    #[inline]
    pub fn node(&self) -> Node<'tree> {
        // SAFETY: Same tree
        unsafe { Node::new(self.cursor.node(), self.tree) }
    }

    /// Gets the field name of the cursor's current node
    pub fn field_name(&self) -> Option<&'static str> {
        self.cursor.field_name()
    }

    /// Get the depth of the cursor's current node relative to the original
    /// node that the cursor was constructed with.
    #[inline]
    pub fn depth(&self) -> u32 {
        self.cursor.depth()
    }

    /// Move the cursor to the first child of the current node and return `true`, or return `false`
    /// if the current node has no children
    #[inline]
    pub fn goto_first_child(&mut self) -> bool {
        self.cursor.goto_first_child()
    }

    /// Move the cursor to the next sibling of the current node and return `true`, or return `false`
    /// if the current node has no next sibling.
    pub fn goto_next_sibling(&mut self) -> bool {
        self.cursor.goto_next_sibling()
    }

    /// Move the cursor to the parent of the current node and return `true`, or return `false`
    /// if the current node is a tree root.
    pub fn goto_parent(&mut self) -> bool {
        self.cursor.goto_parent()
    }
}

impl NodeId {
    /// "Magic" node id for an invalid node
    pub const INVALID: Self = Self(usize::MAX);

    /// Get the id of the given [`tree_sitter::Node`]. See [`tree_sitter::Node::id`]
    #[inline]
    fn of_ts(node: tree_sitter::Node<'_>) -> Self {
        NodeId(node.id())
    }
}

impl From<u64> for NodeId {
    #[inline]
    fn from(value: u64) -> Self {
        NodeId(value as usize)
    }
}

impl From<NodeId> for u64 {
    #[inline]
    fn from(value: NodeId) -> Self {
        value.0 as u64
    }
}

impl Display for NodeId {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "#{}", self.0)
    }
}

impl Clone for TreeParseError {
    #[inline]
    fn clone(&self) -> Self {
        match self {
            TreeParseError::IO(e) => TreeParseError::IO(std::io::Error::from(e.kind())),
            TreeParseError::ParsingFailed => TreeParseError::ParsingFailed,
            TreeParseError::NotUtf8(e) => TreeParseError::NotUtf8(*e),
        }
    }
}

impl From<std::io::Error> for TreeParseError {
    fn from(e: std::io::Error) -> Self {
        TreeParseError::IO(e)
    }
}

impl From<Utf8Error> for TreeParseError {
    fn from(e: Utf8Error) -> Self {
        TreeParseError::NotUtf8(e)
    }
}

impl Display for TreeParseError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            TreeParseError::IO(e) => write!(f, "IO error: {}", e),
            TreeParseError::ParsingFailed => write!(f, "Parsing failed"),
            TreeParseError::NotUtf8(e) => write!(f, "Not UTF-8: {}", e),
        }
    }
}

impl Error for TreeParseError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            TreeParseError::IO(e) => Some(e),
            TreeParseError::ParsingFailed => None,
            TreeParseError::NotUtf8(e) => Some(e),
        }
    }
}

// region special "boilerplate" impls
impl<'tree> Debug for Node<'tree> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self.node)
    }
}
// endregion

/// Strip line breaks from a string of Fortran code.
pub fn strip_line_breaks(src: &str) -> String {
    src.replace('&', "").replace('\n', " ").replace('\r', "")
}
