name: Tests

on:
  push:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/test.yml'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:

  build-macos:
    name: Build and Test (macos)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2.7.8
    - name: "Install Rust toolchain"
      run: rustup show
    - name: "Install cargo nextest"
      uses: taiki-e/install-action@v2.56.10
      with:
        tool: cargo-nextest
    - name: "Install cargo insta"
      uses: taiki-e/install-action@v2.56.10
      with:
        tool: cargo-insta
    - name: "Build"
      run: cargo build --verbose
    - name: "Run tests"
      shell: bash
      env:
        NEXTEST_PROFILE: "ci"
      run: cargo insta test --all-features --workspace --unreferenced reject --test-runner nextest
